/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StateElectorate = {
  stateElectoralName?: string;
  stateElectoralType?: string;
  [k: string]: unknown;
}[];
export type CadastralParcels = {
  propId?: string;
  parcelId?: string[];
  [k: string]: unknown;
}[];

export interface PointAddressResponse {
  data: Address;
  requestTimestamp: string;
  requestDate: string;
  [k: string]: unknown;
}
export interface Address {
  dataset?: string;
  geo?: Geo;
  addressDetails?: AddressDetails;
  addressId: string;
  addressRecordType: "Primary" | "Secondary";
  asgsMain?: ASGSMain;
  commonwealthElectorate?: CommonwealthElectorate;
  localGovernmentArea?: LocalGovernmentArea;
  stateElectorate?: StateElectorate;
  cadastralParcels?: CadastralParcels;
  [k: string]: unknown;
}
export interface Geo {
  geoDatumCode?: string;
  geoFeature?: string;
  geometry?: {
    coordinates?: number[];
    type?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface AddressDetails {
  cadastralIdentifier?: string;
  formattedAddress?: string;
  localityName?: string;
  postcode?: string;
  stateTerritory?: string;
  streetName?: string;
  streetNumber1?: string;
  streetNumber2?: string;
  streetType?: string;
  streetTypeDescription?: string;
  lotIdentifier?: string;
  localityNeighbours?: string;
  gnafLocalityPid?: string;
  gnafStreetLocalityPid?: string;
  aliasPrincipal?: string;
  deliveryPointIdentifier?: string;
  [k: string]: unknown;
}
export interface ASGSMain {
  "2011"?: {
    mbId?: string;
    sa1Id?: string;
    sa2Id?: string;
    sa2Name?: string;
    sa3Id?: string;
    sa3Name?: string;
    sa4Id?: string;
    sa4Name?: string;
    [k: string]: unknown;
  };
  "2016"?: {
    mbId?: string;
    sa1Id?: string;
    sa2Id?: string;
    sa2Name?: string;
    sa3Id?: string;
    sa3Name?: string;
    sa4Id?: string;
    sa4Name?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface CommonwealthElectorate {
  commElectoralName?: string;
  commElectoralPid?: string;
  [k: string]: unknown;
}
export interface LocalGovernmentArea {
  lgaName?: string;
  lgaPid?: string;
  lgaShortName?: string;
  [k: string]: unknown;
}
