/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript. DO NOT MODIFY IT BY HAND. Instead, modify the
 * source JSONSchema file, and run json-schema-to-typescript to regenerate this file.
 */

export interface AddressResponseV3 {
  type?: string;
  geometry?: {
    coordinates?: number[];
    type?: string;
    [k: string]: unknown;
  };
  properties?: {
    addressId?: string;
    formattedAddress?: string;
    postalDeliveryTypeCode?: string;
    postalDeliveryIdentifier?: string;
    siteName?: string;
    complexLevelType?: string;
    complexLevelTypeDescription?: string;
    complexLevelNumber?: string;
    complexUnitType?: string;
    complexUnitTypeDescription?: string;
    complexUnitIdentifier?: string;
    lotIdentifier?: string;
    streetNumber1?: string;
    streetNumber2?: string;
    streetName?: string;
    streetType?: string;
    streetTypeDescription?: string;
    streetSuffix?: string;
    localityName?: string;
    stateTerritory?: string;
    postcode?: string;
    jurisdictionId?: string;
    contributorPropertyId?: string;
    cadastralIdentifier?: string;
    aliasPrincipal?: string;
    addressRecordType?: string;
    geoFeature?: string;
    dataset?: string;
    localityAlias?: {
      [k: string]: unknown;
    }[];
    localityNeighbour?: string[];
    localityId?: string;
    streetLocalityId?: string;
    streetAlias?: {
      [k: string]: unknown;
    }[];
    asgsMain?: {
      censusYear?: number;
      mbId?: string;
      mbCategoryCode?: string;
      mbDwellingCount?: string;
      mbPopCount?: string;
      mbAreaSqm?: string;
      sa1Id?: string;
      sa2Id?: string;
      sa2Name?: string;
      sa3Id?: string;
      sa3Name?: string;
      sa4Id?: string;
      sa4Name?: string;
      gccsaId?: string;
      gccsaName?: string;
      [k: string]: unknown;
    }[];
    asgsRemoteness?: {
      censusYear?: number;
      categoryCode?: string;
      categoryName?: string;
      code?: string;
      pid?: string;
      polygonPid?: string;
      statePid?: string;
      areaSqm?: string;
      dateCreated?: string;
      [k: string]: unknown;
    }[];
    commonwealthElectorate?: {
      commElectoralName?: string;
      commElectoralPid?: string;
      [k: string]: unknown;
    };
    localGovernmentArea?: {
      lgaName?: string;
      lgaPid?: string;
      lgaShortName?: string;
      [k: string]: unknown;
    };
    parcelBundle?: {
      cadastrePid?: string;
      contributorId?: string;
      dateCreated?: string;
      dateModified?: string;
      state?: string;
      lot?: string;
      plan?: string;
      parcelId?: string;
      source?: string;
      contributorStatus?: string;
      titleStatus?: string;
      parcelType?: string;
      baseParcel?: boolean;
      [k: string]: unknown;
    }[];
    propertyBundle?: {
      propertyPid?: string;
      contributorId?: string;
      dateCreated?: string;
      dateModified?: string;
      state?: string;
      source?: string;
      baseProperty?: boolean;
      cadastrePids?: string[];
      parcelIds?: string[];
      [k: string]: unknown;
    }[];
    seifa?: {
      seifa2021Pid?: string;
      dateCreated?: string;
      sa12021Pid?: string;
      population?: string;
      censusYear?: number;
      irsadScore?: string;
      irsadAusRank?: string;
      irsadAusDecile?: string;
      irsadAusPercent?: string;
      irsadStRank?: string;
      irsadStDecile?: string;
      irsadStPercent?: string;
      irsdScore?: string;
      irsdAusRank?: string;
      irsdAusDecile?: string;
      irsdAusPercent?: string;
      irsdStRank?: string;
      irsdStDecile?: string;
      irsdStPercent?: string;
      ierScore?: string;
      ierAusRank?: string;
      ierAusDecile?: string;
      ierAusPercent?: string;
      ierStRank?: string;
      ierStDecile?: string;
      ierStPercent?: string;
      ieoScore?: string;
      ieoAusRank?: string;
      ieoAusDecile?: string;
      ieoAusPercent?: string;
      ieoStRank?: string;
      ieoStDecile?: string;
      ieoStPercent?: string;
      [k: string]: unknown;
    }[];
    stateElectorateBundle?: {
      status?: string;
      stateElectoralPid?: string;
      stateElectoralName?: string;
      stateElectoralClassCode?: string;
      stateElectoralType?: string;
      dateCreated?: string;
      dateGazetted?: string;
      dateEffectiveStart?: string;
      dateEffectiveEnd?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  messages?: string[];
  attribution?: string;
  requestTimeStamp?: number;
  requestDateTime?: string;
  [k: string]: unknown;
}
